title: NatalieðŸˆ Perret'sðŸ« (CheapðŸ’¸) Retroâœ¨ DiariesðŸ““
author: NatalieðŸˆ PerretðŸ«
description: > 
  ðŸˆMeow.
disclaimer1: > 
  Disclaimer 1: Opinions expressed are solely my own and do not express the views or opinions of my employer. 
disclaimer2: > 
  Disclaimer 2: This is mainly a very poorly coded and self-semi-deprecating blog. Take it with a pinch of salt.
url: https://nataly-o-perret.github.io
email: natalie-o-perret@gmail.com

# social links
twitter_username: natalie_perret
github_username: natalie-o-perret
linkedin_username: natalie-perret
stackoverflow_username: "4636721"
rss: rss

kramdown:
  syntax_highlighter_opts:
    block:
    # new version of Minima seems to f*ck up with code rendering when line numbers are enabled =|
      line_numbers: false

show_descriptions: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Pagination
paginate: 3
paginate_path: "posts/page:num"

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
include: ['_pages']
